import type { NextPage } from 'next'
import Head from 'next/head'
import CommonLayout from '@/components/layouts/CommonLayout'
import HomeTemplate from '@/components/templates/home/HomeTemplate'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Daniel Franzese</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel='icon' href='/favicon.png' /> */}
      </Head>

      <CommonLayout>
        <HomeTemplate />
      </CommonLayout>
    </>
  )
}

export default Home
